### ISSUE TITLE
can not run the demo 

### ISSUE THREAD

**Issue by zarchary** [msracver/Deep-Image-Analogy#1]
Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: ../models/vgg19/VGG_ILSVRC_19_layers.caffemodel

**Comment by rozentill** [comment]
Are you running the pre-built exe or the source code (main.cpp)? If you are running the source code, this path of model should be wrong. The models folder is under the project and no need to use '../', just './models/' is ok.

**Comment by rozentill** [comment]
I found a similar issue here : `https://github.com/fyu/dilation/issues/2` .
May it is because the model is not compatibale with your caffe.

**Comment by mamontov-cpp** [comment]
Can you please point to what version of caffe should be used to build a code?
