### ISSUE TITLE
Demo fails (CUDNN_STATUS_SUCCESS (8 vs. 0))

### ISSUE THREAD

**Issue by Poyo-SSB** [msracver/Deep-Image-Analogy#11]
I have downloaded the model and installed CUDA, but the demo still does not run. In another issue, it was mentioned that this project doesn't need cuDNN, but I have it extracted anyway.

```
>C:\Deep-Image-Analogy\windows\deep_image_analogy\exe>deep_image_analogy.exe ../models/ ../demo/content.png ../demo/style.png ../demo/output/ 0 0.5 2 0

[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:78] The total number of bytes read was 574671192
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:78] The total number of bytes read was 574671192
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv5_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv4_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv3_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv2_1.
F0705 13:44:12.492667 10008 cudnn_conv_layer.cu:28] Check failed: status == CUDNN_STATUS_SUCCESS (8 vs. 0)  CUDNN_STATUS_EXECUTION_FAILED
```

**Comment by rozentill** [comment]
Actually the demo was built with cudnn, so cudnn is needed to run it. But you can recompile it without cudnn to reduce some memories.

**Comment by Poyo-SSB** [comment]
I have cuDNN extracted, though. Have I installed it in the wrong place or something?

**Comment by ForeRunner001** [comment]
Hello. I met the same problem. Have you solved this problem yet?

**Comment by rozentill** [comment]
Have you tried to change the value of ratio from 0.5 to 0.2 which could reduce some memories.

**Comment by ad48hp** [comment]
Changing the ratio worked, however i still got some errors.
`Finding nearest neighbor field using PatchMatch Algorithm at layer:conv1_1.
Saving flow result.
Finished finding ann. Time : 21.577
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0918 15:20:57.037252  3020 syncedmem.hpp:31] Check failed: error == cudaSuccess (4 vs. 0)  unspecified launch failure
*** Check failure stack trace: ***`

Lowering ratio to 0.1 worked flawlessly, however the results...
There are no visible changes at ratio this small! xd

**Comment by rozentill** [comment]
Try to disable the time limit (TDR). https://github.com/msracver/Deep-Image-Analogy/issues/25

**Comment by cccusername** [comment]
hello, @rozentill . I try to run the demo but I meet this error too. I don`t know how to disable the time limit. If you could tell me how to disable the time limit,I will appreciate you very much.

**Comment by ad48hp** [comment]
You've probably figured out yourself, but anyways.. It kind of worked yet, my first results weren't as astonishing, but the example was rather suitable for Neural Style Transfer.
Would be noice if the [Stereoscopic Style Transfer](https://arxiv.org/abs/1802.10591) would get a repository with binaries too!

https://www.pugetsystems.com/labs/hpc/Working-around-TDR-in-Windows-for-a-better-GPU-computing-experience-777/
https://forums.geforce.com/default/topic/503962/tdr-fix-here-for-nvidia-driver-crashing-randomly-in-firefox/
Change these three values in _regedit.exe_ to a high value (i used 60000 from about 3-7)

Also, the piece of software has some problems here in there. Rather a minor is that when specifing the models path, the code automatically adds "vgg19/" to it..
It hangs for a while on the `Reading dangerously large protocol message`, too. I tried to copy the 576MB weights file to a simulated RAM disc, and it didn't quickened it much either. Ya could implement batch processing that could save some of the precious time wasted on loading it..

**Comment by cccusername** [comment]
@ad48hp Thank you!!! Although I have solve this problem. lol
