### ISSUE TITLE
Could not run the exe 

### ISSUE THREAD

**Issue by perber** [msracver/Deep-Image-Analogy#15]
Hi, 

we were not able to start the ... application,
because of missing dll files. 
They probably compiled for a other version.

Thanks
Patrick

**Comment by Callidior** [comment]
I had the same problem. They linked the application to CUDA 7.5, but included the libraries for CUDA 8.0.

You could install CUDA 7.5 and copy the correct libraries from there to the directory where `deep_image_analogy.exe` resides. You'll probably need to do the same with CuDNN.

**Comment by scholtes** [comment]
I also changed the 8.0 references to 7.5 (in `windows\deep_image_analogy\deep_image_analogy.vcxproj`) without any problems.

That problem aside, there is also a dependency on [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page), which does not appear to be included in this solution (that or a reference is broken) and causes `WLS.cpp` to not build.  Currently trying to figure out how to get Eigen to build with this project.

**Comment by rozentill** [comment]
Hi, sorry for my mistake. The executable file has been updated but based on another CUDA version, so it could not run. For now, I have update dlls for current executable file. Please check them.
