### ISSUE TITLE
macOS / Linux compile help

### ISSUE THREAD

**Issue by subzerofun** [msracver/Deep-Image-Analogy#2]
**First off, thanks to the whole team for sharing the project!** 

Unfortunately (only concerning this particular project) i have a desktop machine with macOS and couldn't find a way to open/convert the .vcxproj files. I've tried MS [Visual Studio](https://www.visualstudio.com/vs/visual-studio-mac/) and [Visual Studio Code](https://code.visualstudio.com/download) for Mac, but it didn't let me compile the project. These Apps are only shrinked down versions of the original Visual Studio .

Then i tried some tricks and tools to convert the .vcxproj content to regular make or cmake instruction files:

- [vcxproj2cmake](https://github.com/envi/vcxproj2cmake)
- [How to support both vcxproj to cmake on a project?
](https://stackoverflow.com/questions/6649606/how-to-support-both-vcxproj-to-cmake-on-a-project)

All ended with errors, some didn't even get past the first few files in the compile queue... Sadly i have no idea how to write a makefile (or make-config) myself – otherwise i wouldn't bother you.

So my question is: **Did anyone of your team try to compile and run it on Linux or macOS? 
If so, could you please ask them to write down a few steps or a small guide on how to compile it on other systems?**

---

I've waited eagerly to try out the project since the first announcement of the paper on reddit and was a little bit disappointed when i saw that the files were only usable on Windows. But don't get me wrong – i'm still glad that the source files are available!

I have already compiled Caffe (from the official site) a few times with python2 & 3.x support, but for some reason with this project's version i can't get past the last steps of the build (some problem with missing functions for hdf5: "Undefined symbols for architecture x86_64: "_H5LTfind_dataset" and more).

And even if i did get Caffe running, i wouldn't know how to configure and make/compile the files in the `windows/deep_image_analogy/source` folder. I've tried to compile everything with `nvcc` but its either missing some include files – or when i include them manually it throws a lot of errors. 

So any kind of help is deeply appreciated!

**Comment by Shoshin23** [comment]
Second this!
It looks like an awesome paper to explore and have always wanted to implement this. Would love to toy around with it a bit on Linux, and eventually port it to say tensorflow, etc.

**Comment by rozentill** [comment]
Thanks for your interests.
Actually we are working on the linux version of this project now, and if done we will release the linux version. So please wait for a few days.

**Comment by otrimegistro** [comment]
Fork for Linux support:
https://github.com/otrimegistro/Deep-Image-Analogy

**Comment by rozentill** [comment]
Hi, you can check the linux version in the branch 'linux' and run the demo by following the tutorial in README.
