### ISSUE TITLE
failed to run pre-built executable

### ISSUE THREAD

**Issue by enhulu** [msracver/Deep-Image-Analogy#25]
deep_image_analogy.exe ../models/ ../demo/content.png ../demo/style.png ../demo/output/ 0 0.5 2 0
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:78] The total number of bytes read was 574671192
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:78] The total number of bytes read was 574671192
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv5_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv4_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv3_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv2_1.
F1024 12:10:34.443341 32020 cudnn_conv_layer.cu:28] Check failed: status == CUDNN_STATUS_SUCCESS (8 vs. 0)  CUDNN_STATUS_EXECUTION_FAILED
*** Check failure stack trace: ***

**Comment by Micah867** [comment]
I think this is caused by your video card timing out. Many people have been having similar problems running the executable and are concluding it's a memory problem. I rebuilt the exe to disable image resizing and processing 1500px images only need about 5GB, and 2000px images only need about 10GB. The only trouble I've had is with a GeForce card (Tesla works fine in TCC mode) and the Timeout Detection & Recovery (TDR). The TDR can be disabled using the NSight Monitor, and doing so allows a GTX 1070 to process the example images with any ratio and other images with much higher resolution (with a modified binary).

**Comment by enhulu** [comment]
I am using GTX960 4GB... does it mean I cannot run example with ratio higher than 0.2?

**Comment by enhulu** [comment]
Hi, Micah867, could you share some info on how to disable image resizing?

**Comment by Micah867** [comment]
If a single cuda launch takes longer than 2 seconds (the default number, I think) then the program will crash. You can reduce the required time by using smaller images or using a lower ratio. Alternatively, you can disable the time limit (TDR).

A GTX960 has plenty of memory to run the program, but depending on the input image size and ratio it might not finish each individual calculation in less than 2 seconds and crash.
The maximum image size is hardcoded as 700px to prevent crashes. You can just find/replace 700 with 7000000 in DeepAnalogy.cu. Expect the program to crash if you input an image too large.

**Comment by enhulu** [comment]
Thanks @Micah867
