### ISSUE TITLE
Demo File Location

### ISSUE THREAD

**Issue by brainstormapps** [msracver/Deep-Image-Analogy#32]
I cannot find executable file "demo" in folder. (UBUNTU 16.04)
I have installed all dependencies, with cuda and cudnn. Now I want to execute demo file to get test result by using command
./demo deep_image_analogy/models/ deep_image_analogy/demo/content.png deep_image_analogy/demo/style.png deep_image_analogy/demo/output/ 0 0.5 2 0
as you mentioned ...
but I cannot find executable file "demo" in folder...
Can u help me to find its location...
Or How can i build it...
Thanks and regards

**Comment by rozentill** [comment]
Hi, thanks for your interest. Currently we only provide a pre-built executable file for **Windows**. To run a demo in **Ubuntu**, you should build the project yourself. 

For building the whole project, you can check the **Configure & Build** section here: https://github.com/msracver/Deep-Image-Analogy/tree/linux . 

To be more specific, you need to build Caffe at first, then just run our scripts to build our project. After that you will find a 'demo' file.

**Comment by brainstormapps** [comment]
Hi, thanks for your quick response
I have followed all steps mentioned in **Configure & Build** Section.
I have also build Caffe successfully.
after that I do the following steps further to get executable file
1. make build foldre
2. cd build
3. cmake ..
4. make
all commands successfully executed but still no executable file generated...
were is wrong? can you help me?
Thanks and regards

**Comment by rozentill** [comment]
Hi, see if this helps, https://github.com/NVIDIA/nccl/issues/29 .

**Comment by brainstormapps** [comment]
Hi, thanks for response
I have added given flags in CMake.txt file but result is same
Any more suggestion...
thanks and regards
