### ISSUE TITLE
libgdk-x11-2.0.so.0: undefined reference to `XRRFreeMonitors'

### ISSUE THREAD

**Issue by fen328199260** [msracver/Deep-Image-Analogy#39]
hello，

when i run "sh scripts/make_deep_image_analogy.sh" to compile deep_image_analogy, there is an error happened:
```
/lib64/libgdk-x11-2.0.so.0: undefined reference to `XRRFreeMonitors'
/lib64/libgdk-x11-2.0.so.0: undefined reference to `XRRGetMonitors'
```

how should I fix this error?

thanks

**Comment by yankaiqian** [comment]
Please try to install or update the package "libXrandr-devel".

**Comment by fen328199260** [comment]
thanks

**Comment by yuukiii** [comment]
yum install libXrandr-devel
