### ISSUE TITLE
The resultAB.PNG resultBA.png not change,and flowAB.txt flowBA.txt data are all 0,what's happen?

### ISSUE THREAD

**Issue by timtimtm753** [msracver/Deep-Image-Analogy#43]
I follow your step to run source code, but  the resultAB.PNG resultBA.png not change,and flowAB.txt flowBA.txt data are all 0,what's happen?

Below is my setting,

windows/deep_image_analogy/models/ windows/deep_image_analogy/demo/content.png windows/deep_image_analogy/demo/style.png windows/deep_image_analogy/demo/output/ 0 0.5 2 0

and execute result,

[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:78] The total number of bytes read was 574671192
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:78] The total number of bytes read was 574671192
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv5_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv4_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv3_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv2_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv1_1.
Saving flow result.
Finished finding ann. Time : 7.695

**Comment by KhaiLiTay** [comment]
Hi, I encountered exactly the same problem as you described here (output images are the same as input, and flow files contain only zeros).
May I ask how you solved this issue in the end? Any tips or details would be greatly appreciated. Thanks!
