### ISSUE TITLE
Error runnning the exe

### ISSUE THREAD

**Issue by Sugarbank** [msracver/Deep-Image-Analogy#5]
C:\deep_image_analogy\exe>deep_image_analogy.exe ../models/ ../demo/content.png ../demo/style.png ../demo/output/ 0 0.5 2 0
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:78] The total number of bytes read was 574671192
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING ..\src\google\protobuf\io\coded_stream.cc:78] The total number of bytes read was 574671192
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv5_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv4_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv3_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv2_1.
Finding nearest neighbor field using PatchMatch Algorithm at layer:conv1_1.
Saving flow result.
Finished finding ann. Time : 43.575
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0526 19:49:36.182569 10584 syncedmem.hpp:31] Check failed: error == cudaSuccess (4 vs. 0)  unspecified launch failure
*** Check failure stack trace: ***

**Comment by Sugarbank** [comment]
[flowAB.txt](https://github.com/msracver/Deep-Image-Analogy/files/1031457/flowAB.txt)
[flowBA.txt](https://github.com/msracver/Deep-Image-Analogy/files/1031456/flowBA.txt)
![resultab](https://cloud.githubusercontent.com/assets/10692268/26490031/0e8a1a48-424d-11e7-911d-4007f561975c.png)
![resultba](https://cloud.githubusercontent.com/assets/10692268/26490032/0e8afd50-424d-11e7-9bfe-fb4ef29653d6.png)
This was the output

**Comment by pbaylies** [comment]
Try using a smaller image; this happens to me when I run out of GPU memory.

**Comment by Sugarbank** [comment]
Yes this was the issue.Thanks
